[run]
init_cmds = [
	["go", "build"],
	["./610-libs-bra"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = ["view", "../lib"]	    # Directories to watch
watch_exts = [".go", ".html"]		# Extensions to watch
ignore_files = [".*momo.go"]        # Regexps for ignoring specific notifies
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
build_delay = 1500					# Minimal interval to Trigger build event
cmds = [
	["go", "build"],
	["./610-libs-bra"]
]									# Commands to run
